-- AtendaAi__create_table_all.sql
-- Criação de todas as tabelas do sistema Atende-Ai

CREATE TABLE IF NOT EXISTS SEXO (
  ID INT PRIMARY KEY,
  DESCRICAO VARCHAR(20)
  );

CREATE TABLE IF NOT EXISTS PESSOAS (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	ID_SEXO INT,
	EMAIL VARCHAR(200) UNIQUE,
	CONSTRAINT FK_SEXO FOREIGN KEY (ID_SEXO) REFERENCES SEXO (ID),
	CONSTRAINT CHK_IDADE_MINIMA CHECK (EXTRACT(YEAR FROM AGE (CURRENT_DATE, DATA_NASCIMENTO)) >= 16)
);


CREATE TABLE IF NOT EXISTS ESPECIALIDADES (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL,
	PREFIXO CHAR(1) UNIQUE NOT NULL,
	DESCRICAO TEXT,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
	ID SERIAL PRIMARY KEY,
	ID_PESSOA INT NOT NULL,
	ID_ESPECIALIDADE INT,
	MATRICULA VARCHAR(60),
	CARGO VARCHAR(60),
	SALARIO NUMERIC(10, 2),
	ATIVO BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_PESSOA_FUNCIONARIO FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS (ID),
	CONSTRAINT FK_ESPECIALIDADE_FUNCIONARIO FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADES (ID),
	CONSTRAINT CK_SALARIO_FUNCIONARIO CHECK (SALARIO BETWEEN 2000 AND 40000)
);

